spring.application.name=IFCD0014_2026_02_HolaMundoSpringWSJPA

# Puerto del servidor (opcional)
server.port=8080
# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6p8v7h5pdvs739uegj0-a.frankfurt-postgres.render.com:5432/videojuegos_db_b2l9
spring.datasource.username=fpaniagua
spring.datasource.password=QtGn9zuiUTq1gxoIRHqrkTnCon0Smt16
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log del Hikari (Pool de conexiones)
# Con este atributo en modo DEBUG da información del POOL
logging.level.com.zaxxer.hikari=DEBUG
# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
